Updated Readme and Changelog. Deleted installer.
gnFur/Monofoxe pull request #27
Opened 2024-11-09 20:16 UTC by Ne1gh-RR

2024-11-12 16:58 UTC, Martenfur requested changes

2024-11-12 16:58 UTC, Martenfur commented on CHANGELOG.md
> +- **BREAKING CHANGE:** Locked OpenGL on Windows.
"Removed Linux and Mac support form DesktopGL target. You will have to implement abstractions interfaces to make it work again."

2024-11-12 16:58 UTC, Martenfur commented on CHANGELOG.md
> +- Small typos.
Not significant enough to be included in a changelog.

2024-11-12 16:58 UTC, Martenfur commented on CHANGELOG.md
> +- **BREAKING CHANGE:** Removed `MonofoxePlatform` class.
Same thing twice.

2024-11-12 16:58 UTC, Martenfur commented on README.md
> +- Download and install [Visual Studio](https://visualstudio.microsoft.com/) 2022 (VS2019 is no longer supported).
VS2019 is no longer supported is not needed.

2024-11-12 16:58 UTC, Martenfur commented on README.md
> +That's the spirit, but **don't forget to check out Codestyle.cs before contributing!**
wtf why remove all the links

2024-11-12 16:58 UTC, Martenfur commented on README.md
> -* Graphics pipeline and automated batch\vertex buffer management.
Did you just swap their places around? Why?

2024-11-12 16:58 UTC, Martenfur commented on Installer/packInstaller.nsi
Bring these back. Installers are needed as for long as we don't have the alternative. Remove them when dotnet templates will be added.

2024-11-13 04:35 UTC, Ne1gh-RR commented on README.md
> -* Graphics pipeline and automated batch\vertex buffer management.
I brought some meaning in here. From the upper text, it's logical to assume that the engine should be simple for newbies in gamedev. This list primarily covers things that newbies usually don't know.

2024-11-13 04:35 UTC, Ne1gh-RR commented on Installer/packInstaller.nsi
kk

2024-11-13 04:38 UTC, Ne1gh-RR commented on README.md
> +That's the spirit, but **don't forget to check out Codestyle.cs before contributing!**
Quire board isn't relevant anymore? 
idk about twitter

2024-11-13 04:42 UTC, Ne1gh-RR commented on README.md
> -* Graphics pipeline and automated batch\vertex buffer management.
Keep it pls.

2024-11-14 18:17 UTC, closed without merging